spring:
  application:
    name: shopping-cart
  datasource:
    url: jdbc:h2:mem:cart
    username: sa
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml